<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SELECT_provincia</name>
   <tag></tag>
   <elementGuidId>021df257-c3e3-4549-b023-e76109cd66a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='provincia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;provincia&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provincia</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>claslabel</name>
      <type>Main</type>
      <value>formPage_label__BX_42 formPage_control_label__LiPXy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formPage_form_control__Zyfng</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...SALTABUENOS AIRESCIUDAD AUTÓNOMA DE BS. AS.SAN LUISENTRE RÍOSLA RIOJASANTIAGO DEL ESTEROCHACOSAN JUANCATAMARCALA PAMPAMENDOZAMISIONESFORMOSANEUQUÉNRÍO NEGROSANTA FETUCUMÁNCHUBUTTIERRA DEL FUEGOCORRIENTESCÓRDOBAJUJUYSANTA CRUZ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[1]/section[@class=&quot;formPage_formPage__container__5T7cR&quot;]/section[@class=&quot;formPage_formPage__formulario__LCa3y&quot;]/form[1]/div[1]/select[@class=&quot;formPage_form_control__Zyfng&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='provincia']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/section[2]/section/form/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia donde iniciará el trámite:*'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completá el formulario'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centro de Emisión de Licencias donde iniciará el trámite:*'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombres:*'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'provincia' and (text() = 'Seleccione...SALTABUENOS AIRESCIUDAD AUTÓNOMA DE BS. AS.SAN LUISENTRE RÍOSLA RIOJASANTIAGO DEL ESTEROCHACOSAN JUANCATAMARCALA PAMPAMENDOZAMISIONESFORMOSANEUQUÉNRÍO NEGROSANTA FETUCUMÁNCHUBUTTIERRA DEL FUEGOCORRIENTESCÓRDOBAJUJUYSANTA CRUZ' or . = 'Seleccione...SALTABUENOS AIRESCIUDAD AUTÓNOMA DE BS. AS.SAN LUISENTRE RÍOSLA RIOJASANTIAGO DEL ESTEROCHACOSAN JUANCATAMARCALA PAMPAMENDOZAMISIONESFORMOSANEUQUÉNRÍO NEGROSANTA FETUCUMÁNCHUBUTTIERRA DEL FUEGOCORRIENTESCÓRDOBAJUJUYSANTA CRUZ')]</value>
   </webElementXpaths>
</WebElementEntity>
